### ISSUE TITLE
Hollo/Fedify : error with my Iceshrimp account

### ISSUE THREAD

**Issue by kazukyakayashi** [dahlia/hollo#77]
I saw this happen when I was interacting with my Hollo account and my Iceshrimp account.

Hollo/Fedify seems to be looking for information that is inaccessible, non-existent, or in the wrong place.

```
10:17:38.318 DBG fedify·federation·inbox: Object Integrity Proofs are not verified.
10:17:38.333 DBG fedify·sig·key: Key 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj#main-key' found in cache.
10:17:38.335 DBG fedify·federation·inbox: HTTP Signatures are verified.
10:17:38.372 INF fedify·federation·inbox: Activity 'https://social.zarchbox.fr/likes/a1ug3reywd1cs4w0' is enqueued.
10:17:38.373 INF fedify·federation·http: 'POST' '/inbox': 202
10:17:38.387 WRN fedify·runtime·docloader: The "handle" property is deprecated; use "identifier" or "username" instead.
10:17:38.387 WRN fedify·runtime·docloader: The "handle" property is deprecated; use "identifier" or "username" instead.
10:17:38.495 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:38.629 INF fedify·federation·http: 'GET' '/@KazukyAkayashi': 200
10:17:38.726 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/pinned': 200
10:17:38.833 DBG fedify·webfinger·lookup: Fetching WebFinger resource descriptor from 'https://social.zarchbox.fr/.well-known/webfinger?resource=https%3A%2F%2Fsocial.zarchbox.fr%2Fusers%2F9n036nmipdbmdsvj'...
10:17:38.897 INF fedify·federation·http: 'GET' '/.well-known/webfinger?resource=acct:KazukyAkayashi@hollo.zarchbox.fr': 200
10:17:38.901 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:39.023 INF fedify·federation·http: 'GET' '/@KazukyAkayashi': 200
10:17:39.077 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/pinned': 200
10:17:39.100 WRN fedify·federation·http: 'GET' '/.well-known/host-meta': 404
10:17:39.143 INF fedify·federation·http: 'GET' '/.well-known/webfinger?resource=acct:KazukyAkayashi@hollo.zarchbox.fr': 200
10:17:39.218 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:39.289 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:39.346 INF fedify·federation·http: 'GET' '/@KazukyAkayashi': 200
10:17:39.439 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/pinned': 200
10:17:39.466 WRN fedify·federation·http: 'GET' '/.well-known/host-meta': 404
10:17:39.483 INF fedify·federation·http: 'GET' '/@KazukyAkayashi': 200
10:17:39.500 ERR fedify·runtime·docloader: Failed to fetch document: 403 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers' {
  'alt-svc': 'h3=":443"; ma=2592000',
  'cache-control': 'public, max-age=30',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  date: 'Mon, 16 Dec 2024 10:17:39 GMT',
  server: 'Caddy',
  'strict-transport-security': 'max-age=15552000; preload',
  vary: 'Origin'
}
10:17:39.500 ERR fedify·runtime·docloader: Failed to fetch document: 403 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers' {
  'alt-svc': 'h3=":443"; ma=2592000',
  'cache-control': 'public, max-age=30',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  date: 'Mon, 16 Dec 2024 10:17:39 GMT',
  server: 'Caddy',
  'strict-transport-security': 'max-age=15552000; preload',
  vary: 'Origin'
}
10:17:39.501 ERR fedify·vocab: Failed to fetch 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers': FetchError: https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers: HTTP 403: https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers
    at new FetchError (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:26:9)
    at <anonymous> (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:58:19)
    at getRemoteDocument (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:49:34)
    at processTicksAndRejections (native:7:39) {
  url: URL {},
  originalLine: 15,
  originalColumn: 10
}
10:17:39.566 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/pinned': 200
10:17:39.571 INF fedify·federation·http: 'GET' '/.well-known/webfinger?resource=acct:KazukyAkayashi@hollo.zarchbox.fr': 200
10:17:39.617 INF fedify·federation·http: 'GET' '/.well-known/webfinger?resource=acct:KazukyAkayashi@hollo.zarchbox.fr': 200
10:17:39.732 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:39.737 INF fedify·federation·http: 'GET' '/@KazukyAkayashi/0193cef7-8765-73d2-b827-61ac1f35df9b': 200
10:17:39.766 ERR fedify·runtime·docloader: Failed to fetch document: 403 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following' {
  'alt-svc': 'h3=":443"; ma=2592000',
  'cache-control': 'public, max-age=30',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  date: 'Mon, 16 Dec 2024 10:17:39 GMT',
  server: 'Caddy',
  'strict-transport-security': 'max-age=15552000; preload',
  vary: 'Origin'
}
10:17:39.766 ERR fedify·runtime·docloader: Failed to fetch document: 403 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following' {
  'alt-svc': 'h3=":443"; ma=2592000',
  'cache-control': 'public, max-age=30',
  'content-length': '9',
  'content-type': 'text/plain; charset=utf-8',
  date: 'Mon, 16 Dec 2024 10:17:39 GMT',
  server: 'Caddy',
  'strict-transport-security': 'max-age=15552000; preload',
  vary: 'Origin'
}
10:17:39.768 ERR fedify·vocab: Failed to fetch 'https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following': FetchError: https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following: HTTP 403: https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following
    at new FetchError (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:26:9)
    at <anonymous> (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:58:19)
    at getRemoteDocument (/home/freebox/hollo/node_modules/@fedify/fedify/esm/runtime/docloader.js:49:34)
    at processTicksAndRejections (native:7:39) {
  url: URL {},
  originalLine: 15,
  originalColumn: 10
}

```

**Comment by kazukyakayashi** [comment]
These are not errors?

```
10:17:39.501 ERR fedify·vocab: Failed to fetch
```

or 

```
10:17:39.766 ERR fedify·runtime·docloader: Failed to fetch document: 403
```

**Comment by dahlia** [comment]
Oh, I'm sorry. I wasn't aware that I can scroll down the logs!

So… when you look up <https://social.zarchbox.fr/users/9n036nmipdbmdsvj> in the search bar, doesn't it show the result? In my Hollo instance, it shows the result:

![](https://github.com/user-attachments/assets/e4f856a7-3b8b-4827-90b2-4eeed9dc53bf)

**Comment by kazukyakayashi** [comment]
Same result

![2024-12-22_18-10](https://github.com/user-attachments/assets/4de8829c-1d99-441f-bc59-67137184672e)

But the problem is that Fedify seems to be looking for the list of subscriptions :

```
https://social.zarchbox.fr/users/9n036nmipdbmdsvj/following
```

Which leads nowhere and the same for the list of subscribers :

```
FetchError: https://social.zarchbox.fr/users/9n036nmipdbmdsvj/followers: HTTP 403 :
```

No ?

**Comment by dahlia** [comment]
That's no problem! Hollo tries to get the number of following/followers, but if it's impossible it gives up then.

**Comment by kazukyakayashi** [comment]
Yes, but I think I understood why I have this error with my Iceshrimp account and not with other accounts also using Iceshrimp.

My account only gives access to subscribers and subscriptions to people who follow me (I had completely forgotten that I had activated this option), well the problem is that my Hollo account follows my Iceshrimp account so normally I should be able to see the subscribers and subscriptions, so I should have the information which is not the case.

![2024-12-24_11-13](https://github.com/user-attachments/assets/0424c38c-487a-4716-8bbc-d0eaa37bf17c)

I will try to see with other accounts, or put my subscribers and my subscriptions in public to see if the problem comes from there or not.

**Comment by kazukyakayashi** [comment]
I disabled the option that hides subscribers and subscriptions to non-subscribers and no more problem. I think there is a problem since even being subscribed to my Iceshrimp account with my Hollo account I did not see the info.

I do not know if it really comes from Hollo or Iceshrimp (which inherited the way of doing things a little "shaky" from Misskey).
Unfortunately I could not test with other accounts of other software.
