### ISSUE TITLE
Followings import fail (Hollo 0.4.2)

### ISSUE THREAD

**Issue by kazukyakayashi** [dahlia/hollo#85]
Importing subscriptions seems not to work (at least from a .cvs generated by an Iceshrimp instance).
The import of my subscriptions does not seem to work (from a .cvs generated by an Iceshrimp instance). This sends me to an empty page with the following url: `.../accounts/c062bdc9-c764-4bd4-8c58-0e55aa62c027`

I tried with the list of blocked accounts and the import works fine.

```
10:41:24.124 ERR fedify·federation·http: An error occurred while serving request 'POST' 'https://hollo.zarchbox.fr/accounts/c062bdc9-c764-4bd4-8c58-0e55aa62c027/migrate/import': TypeError: Cannot read properties of undefined (reading 'trim')
    at <anonymous> (/home/freebox/hollo/src/pages/accounts.tsx:966:45)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async dispatch (file:///home/freebox/hollo/node_modules/.pnpm/hono@4.6.14/node_modules/hono/dist/compose.js:30:17)
    at async <anonymous> (/home/freebox/hollo/src/login.ts:21:3)
    at async dispatch (file:///home/freebox/hollo/node_modules/.pnpm/hono@4.6.14/node_modules/hono/dist/compose.js:30:17)
    at async trimTrailingSlash2 (file:///home/freebox/hollo/node_modules/.pnpm/hono@4.6.14/node_modules/hono/dist/middleware/trailing-slash/index.js:4:5)
    at async dispatch (file:///home/freebox/hollo/node_modules/.pnpm/hono@4.6.14/node_modules/hono/dist/compose.js:30:17)
    at async onNotFound (file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/x/hono.js:30:13)
    at async #fetch (file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/federation/middleware.js:1255:20)
    at async file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/federation/middleware.js:1206:32
```

**Comment by dahlia** [comment]
Could you provide the very first line of the CSV file you've tried to import?

**Comment by kazukyakayashi** [comment]
There is just an account name, like for the block list.

```
cat Downloads/following-2024-12-31-10-32-12.csv              
admin@social.zarchbox.fr
```

**Comment by kazukyakayashi** [comment]
On my very old account on mamot.fr (mastondon) when I export my followinglist :

```
cat Downloads/following_accounts.csv 
Account address,Show boosts,Notify on new posts,Languages
xxxxxxx@piaille.fr,true,false,
```

Misskey/Iceshrimp have a difference in file construction.

**Comment by dahlia** [comment]
Fixed in [0.4.3](https://github.com/dahlia/hollo/releases/tag/0.4.3).

**Comment by kazukyakayashi** [comment]
There is still a problem, the import starts well but does not seem to work, and it paralyzes the server (inability to post new messages or other), another fact, it does not seem related to the csv provided by Iceshrimp, I wrote some from scratch by hand as Mastodon would output but it did not work either.

CSV : 

```
Account address,Show boosts,Notify on new posts,Languages
peertube@framapiaf.org,true,false,
apertus@mastodon.social,true,false,
NextInpact@mamot.fr,true,false,
LaQuadrature@mamot.fr,true,false,
sigmafrance@mastodon.social,true,false,
play0ad@mastodon.social,true,false,
mobilizon@framapiaf.org,true,false,
datagueule@framapiaf.org,true,false,
PetaPixel@flipboard.com,true,false,

```

A contact also tells me that Pleroma exports the same type of csv as Iceshrimp, so obviously it wouldn't come from there.
