### ISSUE TITLE
Akkoma : Failed to process the incoming activity

### ISSUE THREAD

**Issue by kazukyakayashi** [dahlia/hollo#86]
There is a problem with Akkoma posts apparently.

I can't find [the post](https://bdx.town/notice/ApbOUdefvHc70KSqrw) either and it doesn't appear on the person's profile either (which I follow from my Hollo account)

```
10:40:12.696 ERR fedify·federation·inbox: Failed to process the incoming activity 'https://bdx.town/activities/4431b8e6-0454-43e8-abb1-a895fe2f71c9' (attempt #5); retry...:
JsonLdError [jsonld.SyntaxError]: Invalid JSON-LD syntax; "@id" value must a string.
    at _expandObject (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/expand.js:531:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async api.expand (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/expand.js:251:3)
    at async api.expand (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/expand.js:125:15)
    at async _expandObject (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/expand.js:926:25)
    at async api.expand (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/expand.js:251:3)
    at async jsonld.expand (/home/freebox/hollo/node_modules/.pnpm/jsonld@8.3.3_web-streams-polyfill@3.3.3/node_modules/jsonld/lib/jsonld.js:322:18)
    at async Application.__fromJsonLd__Application__ (file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/vocab/vocab.js:15489:30)
    at async file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/vocab/vocab.js:15453:32
    at async Application.fromJsonLd (file:///home/freebox/hollo/node_modules/.pnpm/@fedify+fedify@1.3.3_web-streams-polyfill@3.3.3/node_modules/@fedify/fedify/esm/vocab/vocab.js:15451:16) {
  details: { code: 'invalid @id value', value: null }
}
```

**Comment by dahlia** [comment]
It needs to be changed in Akkoma.  In their actor object (<https://bdx.town/users/clovis>):

```json
{
  "@context": [
    "https://www.w3.org/ns/activitystreams",
    "https://bdx.town/schemas/litepub-0.1.jsonld",
    {
      "@language": "und"
    }
  ],
  "alsoKnownAs": [],
  "attachment": [
    {
      "name": "Localization",
      "type": "PropertyValue",
      "value": "Bdx"
    },
    {
      "name": "Writings",
      "type": "PropertyValue",
      "value": "<a href=\"https://noircir.bdx.town/clovis/\" rel=\"ugc\">https://noircir.bdx.town/clovis/</a>"
    },
    {
      "name": "Contact",
      "type": "PropertyValue",
      "value": "clovis@bdx.town"
    },
    {
      "name": "Aider le serveur",
      "type": "PropertyValue",
      "value": "<a href=\"https://ko-fi.com/bdxtown\" rel=\"ugc\">https://ko-fi.com/bdxtown</a>"
    }
  ],
  "capabilities": {},
  "discoverable": true,
  "endpoints": {
    "oauthAuthorizationEndpoint": "https://bdx.town/oauth/authorize",
    "oauthRegistrationEndpoint": "https://bdx.town/api/v1/apps",
    "oauthTokenEndpoint": "https://bdx.town/oauth/token",
    "sharedInbox": "https://bdx.town/inbox"
  },
  "featured": "https://bdx.town/users/clovis/collections/featured",
  "followers": "https://bdx.town/users/clovis/followers",
  "following": "https://bdx.town/users/clovis/following",
  "icon": {
    "type": "Image",
    "url": "https://media.bdx.town/media/0f8f73bba83a64c218744c77f1ba3248ef9093cfb98bc55ef0b30eef78d66454.jpg"
  },
  "id": "https://bdx.town/users/clovis",
  "image": {
    "type": "Image",
    "url": "https://media.bdx.town/media/359c5ded4072ac30e5d158a0d19e65e2918636f9b87f7ff50306e42d55e81b56.png"
  },
  "inbox": "https://bdx.town/users/clovis/inbox",
  "manuallyApprovesFollowers": false,
  "name": "Clovis :bdx_town:",
  "outbox": "https://bdx.town/users/clovis/outbox",
  "preferredUsername": "clovis",
  "publicKey": {
    "id": "https://bdx.town/users/clovis#main-key",
    "owner": "https://bdx.town/users/clovis",
    "publicKeyPem": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqv/bi+HKMO5yctKFnGSV\naAYLWi9rAgAx/BJ3zzSJtn1InRMBYPcY4+ohfVVtp43oaUdgpWS4mKi+E9Hp42XO\nFQSbVlgd8jCg9LoZ/cEYOe2op2X/OQakxQGdjKJYIml2DmfrsUfRpFZWNG61CLxx\ncDos1Pm139silyvkz8i6NYigjezKP5Q6GE1b84U3EneZslgqt3Wjs6TuQ4rGS5vs\n7jeTBJZPn8iCQmxwSo5lz0Ei6xNr+JdMaYKtsORtyEY1gqF5jJGlBHcdJveTbUjc\nPZGqveXlgmOWE5L2MYN6PmDxCSJQGnfCoj474ESrTgms4itNWhDEjP3CObXBEL1x\ndwIDAQAB\n-----END PUBLIC KEY-----\n\n"
  },
  "summary": "<a href=\"http://BDX.town\">BDX.town</a> admin<br/><br/>Créons des trucs cools ensemble.<br/>Anarcho-mitterandiste, j&#39;sais même pas si ça existe.<br/>Crypto-hipster à bande magnétique.<br/><br/>Mangane, an Akkoma frontend, contributor: <a href=\"https://github.com/BDX-town/Mangane\">https://github.com/BDX-town/Mangane</a><br/>Noircir, a lightweight and ecofriendly (at least that&#39;s the goal) blog system, contributor: <a href=\"https://github.com/BDX-town/Noircir\">https://github.com/BDX-town/Noircir</a>",
  "tag": [
    {
      "icon": {
        "type": "Image",
        "url": "https://bdx.town/emoji/bdx.town/mini_logo_color.png"
      },
      "id": null,
      "name": ":bdx_town:",
      "type": "Emoji",
      "updated": "1970-01-01T00:00:00Z"
    }
  ],
  "type": "Person",
  "url": "https://bdx.town/users/clovis"
}
```

Their `Emoji` object has an invalid `id` (which is `null`):

```json
{
  "icon": {
    "type": "Image",
    "url": "https://bdx.town/emoji/bdx.town/mini_logo_color.png"
  },
  "id": null,
  "name": ":bdx_town:",
  "type": "Emoji",
  "updated": "1970-01-01T00:00:00Z"
}
```

**Comment by dahlia** [comment]
They already have an [issue about this](https://akkoma.dev/AkkomaGang/akkoma/issues/848), and also a [patch to fix it](https://akkoma.dev/AkkomaGang/akkoma/pulls/850).  We're closing this.
